default:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  database: designer
  synchronize: true
  entities: 
    - src/entities/mysql/*.ts
  migrations: 
    - src/migration/mysql/*.ts
  migrationsTableName: custom_migration_table
  cli:
    entitiesDir: src/entities/mysql
    migrationsDir: src/migration/mysql

mongo:
  type: mongodb
  host: localhost
  port: 27017
  database: designer
  synchronize: true
